version: '2'
services:
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "80:80"
    links:
      - app
    restart: always 
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    volumes:
      - ./:/var/www
    links:
      - database
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
    restart: always 
  database:
    image: mysql:5.6
    environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: homia
    ports:
        - "33070:3306"
    restart: always 